### ISSUE TITLE
Local Avatar with S3 Offloaded not correct image url

### ISSUE THREAD

**Issue by channchetra** [10up/simple-local-avatars#99] opened 2022-02-16 08:12 UTC
### Describe your question

Hello,
I'm using Simple Local Avatar with all media offloaded to S3 with [WP Offload Media by DELICIOUS BRAINS](https://deliciousbrains.com/wp-offload-media/) after offloaded all media all image in avatar are broke I'm inspected in img tag of avatar it's show something like this:
`<img alt="" src="https://ams.com.kh/central/s3://central/media/Heng-Sambath-116x116.png" srcset="https://ams.com.kh/central/s3://central/media/Heng-Sambath-232x232.png 2x" class="avatar avatar-116" height="116" width="116" loading="lazy">`
It's should be like this:
`<img alt="" src="https://asset.ams.com.kh/central/media/Heng-Sambath-116x116.png" srcset="https://asset.ams.com.kh/central/media/Heng-Sambath-232x232.png 2x" class="avatar avatar-116" height="116" width="116" loading="lazy">`
All media working fine every where only in Avatar that not work there's any help?
Thank you

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by channchetra** [comment] 2022-02-26 03:55
I found someone has that problem too on [wp support forum](https://wordpress.org/support/topic/wp-offload-s3-with-avatars/) but there are no solution 😥

**Comment by channchetra** [comment] 2022-03-04 06:58
I'm using Lite version of WP Offload Media https://wordpress.org/plugins/amazon-s3-and-cloudfront/

**Comment by faisal-alvi** [comment] 2022-03-04 10:32
@channchetra thank you for reporting the issue. I would like to help you asap but unfortunately, the option to offload existing media to s3 is not available in the free version of the "WP Offload Media" plugin.

When I upload a new avatar, it uploads to s3 and also loads correctly on the site. It seems like the issue is with the existing avatars. I would not be fully able to regenerate the issue until I'm able to use the offload the existing media feature of the plugin. However, I have looked into the code and it seems like adding the following code on line number `217` in the `simple-local-avatars/includes/class-simple-local-avatars.php` file may fix this issue for you.

```
$local_avatars[ $size ] = str_replace( '/s3://central', '', $local_avatars[ $size ] );
$local_avatars[ $size ] = str_replace( '//ams', '//asset.ams', $local_avatars[ $size ] );
```
Paste it before the return statement here.

https://github.com/10up/simple-local-avatars/blob/0729cf73d5237ed0797379b01df0c19eca383fbe/includes/class-simple-local-avatars.php#L217-L218

This is not the best solution but until the official fix is made, I thought this may help you.

**Comment by jeffpaul** [comment] 2022-03-04 21:47
@faisal-alvi could https://github.com/deliciousbrains/wp-offload-ses-lite be an option for testing to see if the issue occurs there?

**Comment by jeffpaul** [comment] 2022-03-04 21:47
@mattgrshaw pinging you here on this WP Offload Media compat issue, curious if you're able to help triage given your access to the private paid version?

**Comment by channchetra** [comment] 2022-03-07 05:52
Thank @faisal-alvi for help yes now I'm using that same way you mention to solve the problem. Hope we have better solution soon

**Comment by mattgrshaw** [comment] 2022-03-07 16:29
Thanks for the heads up @jeffpaul. Pinging @ianmjones / @eriktorsner here, they'll be much better equipped to help out with this one.

**Comment by eriktorsner** [comment] 2022-03-07 17:05
Thanks for the ping @mattgrshaw. 

I'm setting up a local test for this later tonight to tomorrow morning. Stay tuned.

**Comment by faisal-alvi** [comment] 2022-04-14 10:39
@eriktorsner just following up to know if you get enough time to look at this issue?

**Comment by faisal-alvi** [comment] 2022-05-18 13:11
Closing the issue, will consider it later if we get more reports. Please feel free to re-open if required.

**Closed as completed by faisal-alvi** 2022-05-18 13:11 UTC
Labels: help wanted, resolution:wontfix

**Comment by N0N4M3BNS** [comment] 2023-08-26 07:19
Hi, I have the same issues. So I tried to add an implementation like the previous message. Not working can help me.

> @channchetra thank you for reporting the issue. I would like to help you asap but unfortunately, the option to offload existing media to s3 is not available in the free version of the "WP Offload Media" plugin.
> 
> When I upload a new avatar, it uploads to s3 and also loads correctly on the site. It seems like the issue is with the existing avatars. I would not be fully able to regenerate the issue until I'm able to use the offload the existing media feature of the plugin. However, I have looked into the code and it seems like adding the following code on line number `217` in the `simple-local-avatars/includes/class-simple-local-avatars.php` file may fix this issue for you.
> 
> ```
> $local_avatars[ $size ] = str_replace( '/s3://central', '', $local_avatars[ $size ] );
> $local_avatars[ $size ] = str_replace( '//ams', '//asset.ams', $local_avatars[ $size ] );
> ```
> 
> Paste it before the return statement here.
> 
> https://github.com/10up/simple-local-avatars/blob/0729cf73d5237ed0797379b01df0c19eca383fbe/includes/class-simple-local-avatars.php#L217-L218
> 
> This is not the best solution but until the official fix is made, I thought this may help you.

**Comment by faisal-alvi** [comment] 2023-08-29 10:51
Hey @frontend-bravo-net-solution, thanks for getting in touch! Could you share the steps you followed when the issue occurred? It would be really helpful if you could also send us screenshots or describe the error you encountered. This way, we can assist you better!
